sudo: required
dist: trusty
language: go
go_import_path: istio.io/mixer

go:
- 1.7.x

jdk:
- oraclejdk8

env:
  global:
  - BAZEL_VERSION=0.4.2

addons:
  apt:
    packages:
    - wget

cache:
  directories:
  - $HOME/bazel/install
  - $HOME/bazel/outbase

before_install:
- mkdir -p ${HOME}/bazel/install
- cd ${HOME}/bazel/install
- wget --no-clobber "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb"
- chmod +x bazel_${BAZEL_VERSION}-linux-x86_64.deb
- sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb
- sudo apt-get -f install -qqy
- cd ${TRAVIS_BUILD_DIR}
- mv .bazelrc .bazelrc.orig
- cat .bazelrc.travis .bazelrc.orig > .bazelrc

script:
- bazel --output_base=$HOME/bazel/outbase test //...
- bin/linters.sh
- bin/codecov.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
- docker/travis_gcloud.sh

notifications:
  slack: istio-dev:wEEEbaabdP5ieCgDOFetA9nX
